services:
  database:
    container_name: database
    image: postgres:15.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=status_dashboard
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.6
    restart: always
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_LOG_CONSOLE_LEVEL=all
    ports:
      - "8080:8080"
    volumes:
      - keycloak:/opt/keycloak/data/
    command: start-dev

volumes:
  db:
  keycloak:
